### ISSUE TITLE
options for displaying large job output?

### ISSUE THREAD

**Issue by benodom** [josacar/lita-jobs#3]
Hello,

Thanks for the gem.  I am making use of this, but I find that Slack's limitation on message size is a problem for us.  Most of our jobs can't be displayed in one message, and I will be looking for ways to display these, either with links to static files served via nginx, or ideally with the ability to create a snippet/attachment in slack with the jobs output file.  Let me know if you have feedback, thanks!

**Comment by josacar** [comment]
We are suffering this issue too, Slack's RTM api limits each message to 10KB which can be too small sometimes. The issue there is maybe of lita or the adapter itself, for slack maybe offering an API to paste text as it happened in Campfire adapter for example ( just introspect if it's a multiline message or not ).

I miss this feature too, maybe @jimmycuadra can give us some light :)

**Comment by jimmycuadra** [comment]
I haven't looked into it yet, but I do know that's support for attachments is being worked on for the Hubot adapter. Take a look at slackhq/hubot-slack#108 and slackhq/hubot-slack#148.

**Comment by benodom** [comment]
@josacar @jimmycuadra thanks for the input. I am going to fork lita-slack and add a conditional here: https://github.com/kenjij/lita-slack/blob/master/lib/lita/adapters/slack/rtm_connection.rb#L103 that will auto-convert the large message into an attachment instead of dropping it on the floor and raising an exception.  Thoughts?

**Comment by jimmycuadra** [comment]
I'm not sure if it will fit your use case, but lita-slack should probably not simply raise an exception when a message is larger than Slack's limit – it should sent it in chunks. I believe this is what the Hubot adapter does if you want to look at that for an example.

I also think it'd be useful to somehow expose Slack's attachment API to Lita, but I don't want to clutter this issue with discussing the details of that. An issue on lita-slack would be more appropriate.

**Comment by benodom** [comment]
thanks @jimmycuadra I'll open up an issue on lita-slack to continue this thread.
